### ISSUE TITLE
Commands should provide feedback

### ISSUE THREAD

**Issue by micmania1** [silverstripe/sspak#25] opened 2015-01-13 22:05 UTC
I've just ran sspak load and it worked, but there was no response to tell me that it had worked. This may be the case for other commands too. 

Commands should provide feedback after they have ran.

**Comment by camfindlay** [comment] 2016-04-04 22:19
+1

**Comment by mlewis-everley** [comment] 2016-07-14 11:15
I agree, but there should be a "silent" option that can be run (for if we use this via cron and don't want to fill our logs with completion messages).

**Comment by dhensby** [comment] 2017-12-19 16:35
duplicate of #8

**Closed by dhensby** 2017-12-19 16:35 UTC
